### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'load_translations'

### ISSUE THREAD

**Issue by Neko-no-akuma-TW** [a3510377/discord-py-cord-template#11]
### 摘要 - Summary

無該屬性

### 問題 - Problem

Command raised an exception: AttributeError: 'WindowsPath' object has no attribute 'load_translations'

### 最小的問題展示程式 - Minimal Reproducible Code

![image](https://user-images.githubusercontent.com/80331285/230881716-cde86634-db0e-4860-9586-adec60fc6320.png)
在執行reload這個文字指令時觸發
已經協助修改，請更新

### 預期狀況

不應該出現這個錯誤

### 實際狀況 - Actual Results

齣戲了這個錯誤

### Checklist

- [X] 我已經在打開的問題中搜索，且並無重複。 I have searched the open issues for duplicates.

- [X] 上述資料中皆無 TOKEN 洩漏。 There is no TOKEN leakage in the above data.

### 備註 - Remark

已經協助修改，請更新上去，檔案名稱等也已附上

**Comment by qmkcat** [comment]
Thanks for reporting, fixed in #12
感謝回報，已於 #12 修復
