### ISSUE TITLE
多個錯誤

### ISSUE THREAD

**Issue by Neko-no-akuma-TW** [a3510377/discord-py-cord-template#13]
### 摘要 - Summary

多個錯誤

### 問題 - Problem

通常都是屬性錯誤，少部分例外
![image](https://user-images.githubusercontent.com/80331285/230889252-f3b75a2b-6e19-4c38-8ba7-889caeb0bdea.png)
![image](https://user-images.githubusercontent.com/80331285/230889620-aecffe9a-d0fc-4962-81ef-e5728bfbe8f7.png)
上方的guild_locale是我自己改的，我有把它改回來(程式碼)，請不要理會錯誤內的guild_locale，最主要的錯誤是if kwargs
![image](https://user-images.githubusercontent.com/80331285/230889833-99d264eb-81dd-447b-b39d-dd261054b31b.png)
上方的錯誤我並沒有做修改，因為我看不出來
還有，在bot\cogs\admin\clear.py:15、bot\cogs\admin\clear.py:25，應該要改成str
還有還有，bot\cogs\admin\clear.py:27應該要改成`content = message.content.strip()`

### 最小的問題展示程式 - Minimal Reproducible Code

請看上面

### 預期狀況

這些錯誤都不應該出現

### 實際狀況 - Actual Results

出現了以上錯誤

### Checklist

- [X] 我已經在打開的問題中搜索，且並無重複。 I have searched the open issues for duplicates.

- [X] 上述資料中皆無 TOKEN 洩漏。 There is no TOKEN leakage in the above data.

### 備註 - Remark

所有的備註幾乎都在圖片下面，請詳細閱讀

**Comment by qmkcat** [comment]
Thanks for reporting, fixed in #14 
感謝回報，已於 #14 修復
